# Use a base image with Python 3 and Ubuntu (adjust the base image as needed)

ARG PYTHON_VERSION

FROM python:${PYTHON_VERSION}-slim AS builder

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-pip


# Build the final image with a minimal base
FROM python:${PYTHON_VERSION}-slim AS final

RUN pip3 install -U pip redis rq

ENTRYPOINT ["bash", "-c", "rq worker -v --url redis://redis-cache:6379"]
