name: frappe-compose

x-common-redis: &common-redis
  ports:
    - target: 6379
      published: "6379"
      mode: ingress
  networks:
    - thebridge


services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb_frappe_container
        volumes:
            - type: bind
              source: ./infra/config/my.cnf
              target: /etc/mysql/my.cnf
            - type: volume
              source: maria-volume
              target: /var/lib/mysql
        environment:
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
#          - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
          - MARIADB_DATABASE=${MARIADB_DATABASE}
          - MARIADB_USER=${MARIADB_USER}
          - MARIADB_PASSWORD=${MARIADB_PASSWORD}
#          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#          - MYSQL_DATABASE=${MYSQL_DATABASE}
#          - MYSQL_USER=${MYSQL_USER}
#          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#        healthcheck:
#          test: mariadb-admin ping -h localhost --password=${MARIADB_PASSWORD}
#          interval: 10s
#          retries: 5
        deploy:
          restart_policy:
            condition: on-failure
        ports:
            - target: 3306
              published: "3306"
              mode: ingress
        networks:
            - thebridge

    redis-cache:
        <<: *common-redis
        image: redis:latest
        container_name: redis-cache

    redis-rq:
        <<: *common-redis
        build:
            context: .
            dockerfile: Dockerfile.rq
            args:
              PYTHON_VERSION: "${PYTHON_VERSION}"
        environment:
          - PYTHON_VERSION=${PYTHON_VERSION}
        container_name: redis_frappe_rq_container
        ports:
          - target: 6380
            published: "6380"
            mode: ingress

    frappe:
      entrypoint: ["bash", "-c", "chmod +x bench_setup_scripts.sh && sh bench_setup_scripts.sh"]
      working_dir: /app/bench_apps
      build:
        context: .
        dockerfile: Dockerfile
        args:
          PYTHON_VERSION: "${PYTHON_VERSION}"
          FRAPPE_BRANCH: "${FRAPPE_BRANCH}"
      environment:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - FRAPPE_BRANCH=${FRAPPE_BRANCH}
        - SHELL=/bin/bash
#        - MYSQL_DATABASE=${MYSQL_DATABASE}
#        - MYSQL_USER=${MYSQL_USER}
        - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
      depends_on:
        - mariadb
        - redis-cache
        - redis-rq
      volumes:
        - workspace:/workspace:cached
        - type: bind
          source: bench_apps/
          target: /app/bench_apps/
        - type: bind
          source: infra/config/my.cnf
          target: /usr/local/etc/my.cnf
      ports:
        - 8000-8005:8000-8005
        - 9000-9005:9000-9005
      networks:
        - thebridge

networks:
    thebridge:
        driver: bridge

volumes:
    maria-volume:
      driver: local
    workspace:
      driver: local
