name: frappe-compose

x-common-redis: &common-redis
  ports:
    - target: 6379
      published: "6379"
      mode: ingress
  networks:
    - thebridge


services:
    mariadb:
        image: mariadb:latest
        container_name: mariadb_frappe_container
        volumes:
            - type: bind
              source: ./infra/config/my.cnf
              target: /etc/mysql/my.cnf
            - type: volume
              source: maria-volume
              target: /var/lib/mysql
            - type: bind
              source: ./bench_apps/mariadb_config.sh
              target: /bin/mariadb_config.sh
        environment:
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
          - MARIADB_DATABASE=${MARIADB_DATABASE}
          - MARIADB_USER=${MARIADB_USER}
          - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        healthcheck:
          test: mariadb-admin ping -h localhost -u root --password=${MARIADB_ROOT_PASSWORD}
          interval: 10s
          retries: 5
        deploy:
          restart_policy:
            condition: on-failure
        ports:
            - target: 3306
              published: "3306"
              mode: ingress
        networks:
            - thebridge

    redis-cache:
        <<: *common-redis
        image: redis:latest
        container_name: redis-cache

    redis-rq:
        <<: *common-redis
        build:
            context: .
            dockerfile: Dockerfile.rq
            args:
              PYTHON_VERSION: "${PYTHON_VERSION}"
        environment:
          - PYTHON_VERSION=${PYTHON_VERSION}
        container_name: redis_frappe_rq_container
        ports:
          - target: 6380
            published: "6380"
            mode: ingress

    frappe:
      entrypoint: ["bash", "-c", "./bootstrap.sh"]
      working_dir: /app/bench_apps
      build:
        context: .
        dockerfile: Dockerfile
        args:
          PYTHON_VERSION: "${PYTHON_VERSION}"
          FRAPPE_BRANCH: "${FRAPPE_BRANCH}"
      environment:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - FRAPPE_BRANCH=${FRAPPE_BRANCH}
        - SHELL=/bin/bash
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        - MARIADB_DATABASE=${MARIADB_DATABASE}
        - MARIADB_USER=${MARIADB_USER}
      depends_on:
        - mariadb
        - redis-cache
        - redis-rq
      volumes:
        - workspace:/workspace:cached
        - type: bind
          source: bench_apps/
          target: /app/bench_apps/
        - type: bind
          source: infra/config/my.cnf
          target: /usr/local/etc/my.cnf
        - type: bind
          source: bench_apps/bootstrap.sh
          target: /app/bench_apps/bootstrap.sh
      ports:
        - 8000-8005:8000-8005
        - 9000-9005:9000-9005
      networks:
        - thebridge

networks:
    thebridge:
        driver: bridge

volumes:
    maria-volume:
      driver: local
    workspace:
      driver: local
